export { default as Home } from './Home'
export { default as About } from './About'
export { default as Awards } from './Awards'
export { default as Board } from './Board'
export { default as Gallary } from './Gallary'
export { default as Services } from './Services'
